CREATE DATABASE nzhome;

CREATE TABLE Users(
    UserID SERIAL PRIMARY KEY,
    AccessLevel SMALLINT NOT NULL,
    FirstName VARCHAR(20) NOT NULL,
    LastName VARCHAR(20) NOT NULL,
    Email VARCHAR(20) NOT NULL,
);

CREATE TABLE 